# coding=utf-8

franchise_a = ['Dark', 'Steel', 'Modern', 'Virtua', 'Burning', 'Half', 'Dead', 'Demon', 'Iron',
    'Zero', 'Lincoln', 'Rock', 'Guitar', 'Brütal', 'FIFA', 'Madden', 'Street', 'Full', 'Twisted',
    'Dungeon', 'Team', 'Hard', "Mirror's", 'Love', 'Saints', 'Dragon', 'Black', 'L.A.', 'Mass',
    'Night', 'Solar', 'Bad', 'Battle', 'Rhythm', 'Renegade', 'Puzzle', 'Mad', 'Geometry',
    'AI', 'Blueberry', 'Red', 'Monster', 'Bit', 'Beat', 'Zombie', 'Tentacle', 'Indigo', 'Cool',
    'Alien', 'Mr.', 'Tomb', 'Universe', 'Swarm', 'Frozen', 'Hammer', 'Killing', 'Bullet', 'Baby',
    'Divine', 'Beyond', 'Cave', 'Counter', 'Missile', 'Crayon', 'Dangerous', 'Darkest', 'Day of',
    'Call of', 'Alpha', 'Prime', 'Earth', 'Chrono', 'Grand', 'Advance', 'Super', 'Total', 'Deadly',
    'Desert', 'Unreal', 'Doki Doki', 'Chu Chu', 'Poker', 'Gal', 'Rock of', 'King', 'Donkey',
    "Assassin's", 'Warp', 'War', 'Medal of', 'Jet Set', 'Oregon', 'Mercenary', 'Tecmo', 'Mega',
    'Dance Dance', 'Dancing', 'Party', 'S.O.S.', 'Lucky', 'Meat', 'Tiny', 'Face', 'Everyday',
    'PixelJunk', 'Angry', 'Little', 'Katawa', 'King of', 'Resident', 'Mario', 'Big', 'Jet',
    'Ace', 'End of', 'Space', 'Metal', 'Devil', 'Shin Megami', 'Sonic', 'Spy', 'Pocket', 'Royal',
    'Ghost', 'Pipe', 'Tetris', 'World of', 'Old', 'Codename', 'Tekken', 'Real', 'Heavy', 'Dance',
    'Bionic', 'Metal Gear', 'Portable', 'Terror', 'Infinity', 'Extreme', 'Castle', 'Wind-up',
    'Office', 'Dino', 'Galactic', 'North American', 'Project', 'Ninja', 'Mortal', 'Cosmic',
    'Calamity', 'Continuum', 'Otomedius', 'Test', 'Men of', 'Fortune', 'NASCAR', 'Touhou', 'Ridge',
    'Rainbow', 'Sim', 'Guilty', 'Silent', 'Fire', 'MLB', 'Wing', 'River City', 'Fatal', 'Samurai',
    'Hot', 'Pet', 'Adventure', 'Thunder', 'Lode', 'Incredible', 'Micro', 'Golden', 'Raving',
    'Family', 'Close', 'Time', 'Jagged', 'Original', 'Electric', 'Rave', 'Wild', 'Red Dead',
    'River', 'Burger', 'High-Res', 'Glory', 'Hidden', 'Loaded', 'Rugby', 'Killer', 'Power',
    'X', 'Dr.', 'Carnage', 'Kingdom', 'Ogre', 'Pokémon', 'Moto', 'Elevator', 'Music', 'Curious',
    'Dynasty', 'Final', 'Supreme', 'Legendary', 'Road', 'Superbike', 'Motocross', 'Star',
    'Trauma', 'Jimmy', 'Age of', 'Jungle', 'Animal', 'Naughty', 'Ancient', 'Smash', 'Item',
    'Monday Night', 'Cooking', 'Pro', 'Spirit', 'Exotic', 'System', 'Criminal', 'Mystic', 'Elder',
    'Ocarina of', 'Theme', 'Hyperdimension', "Kirby's", 'Epic', "Dante's", 'Mecha', "Yoshi's",
    'Paper'
    ]

franchise_b = ['Souls', 'Storm', 'Batallion', 'Warfare', 'Tennis', 'Fighter', 'Retribution',
    'Life', 'Death', 'Space', 'Blade', 'Brigade', 'Mania', 'Wing', 'Flame', 'F.O.R.C.E.', 'Band',
    'Hero', 'Legend', 'Football', 'Tentacle', 'Mansion', 'Heroes', 'Hour', 'Forge', 'Drive',
    'Fortress', 'Reset', 'Edge', 'Pachinko', 'Plus', 'Arena', 'Descent', 'Noire', 'Ops', 'Rain',
    'Age', 'Effect', 'Sky', 'Company', 'Paradise', 'Heaven', 'Agent', 'World', 'Wars', 'Flight',
    'War', 'Garden', 'Hazard', 'Faction', 'Trucks', 'Trip', 'Waves', 'Vision', 'Driver', 'Castle',
    'Prophecy', 'Swarm', 'Raider', 'Sandbox', 'Smasher', 'Synapse', 'Fight', 'Trick', 'Dogma',
    'Floor', 'Candy', 'Supremacy', 'Land', 'Story', 'Strike', 'Command', 'Physics', 'Shadows',
    'High-School Girls', 'Days', 'Messiah', 'Duty', 'Trigger', 'Mario', 'Horses', 'Orchestra',
    'Overture', 'City', 'Premonition', 'Tournament', 'Panic', 'Rocket', 'Night', 'Gun', 'Ages',
    'Kong', 'Attack', 'Race', 'Planet', 'Creed', 'Men', 'Honor', 'Radio', 'Trail', 'Skull', 'Bowl',
    'Girls', 'Man', 'Revolution', 'Stage', 'Party', '☆  Star', 'Boy', 'Void', 'Mesa', 'Tower',
    'Journey', 'Flow', 'Shooter', 'Eden', 'Monsters', 'Wings', 'Birds', 'Big Planet', 'Shoujo',
    'Evil', 'Dust', 'Rigs', 'Force', 'Combat', 'Soccer', 'Survivor', 'Tensei', 'Tag', 'Fiction',
    'Agents', 'Rumble', 'Fighters', 'Warfighter', 'Dream', 'Republic', 'Crisis', 'Cricket',
    'Central', 'Karaoke', 'Empire', 'Commando', 'Stalker', 'League', 'Crashers', 'Darkness',
    'Knight', 'Championship', 'Giraffe', 'Yeti', 'D-Day', 'Run', 'Core', 'Fishing', 'Adventure',
    'Adventures', 'Hunter', 'Hunting', 'Hitman', 'Friends', 'Rub', 'Racing', 'Gaiden', 'Kombat',
    'Shift', 'Excellent', 'Street', 'NFL', 'Quest', 'Hill', 'Emblem', 'Invaders', 'Commander',
    'Fury', 'Ransom', 'Showdown', 'Recon', 'Shots', 'Brothers', 'Wolfenstein', 'Shop', 'Sports',
    'Mission', 'Front', 'Island', 'Jam', 'Runner', 'Machines', 'Machine', 'Breed', 'Lair', 'Axe',
    'Rabbids', 'Feud', 'Alliance', 'Defense Force', 'Kings', 'Eye', 'Master', 'Revolver', 'Time',
    'Raid', 'Filter', 'Soldier', 'Army', 'Instinct', 'Hearts', 'Annihilation', 'Stadium', 'Action',
    'Village', 'Box', 'Warrior', 'Warriors', 'Fantasy', 'Ruler', 'Center', 'Dave', 'Paint',
    'Forest', 'Beat', 'Crossing', 'Bass', 'TV', 'Dawn', 'Mama', 'Skater', 'Pilot', 'Raiders',
    'Farm', 'Shock', 'Origins', 'Underworld', 'Scrolls', 'Colossus', 'Mask', 'Snowboarding',
    'Neptunia', 'Snap', 'Dash', 'Attorney', 'Conquest'
    ]

name = ['Ultimate %s', 'The %s', '%s', '%s: Reckoning', '%s 2', '%s 3', '%s 4', '%s 5', '%s 9',
    '%s: Episode Three', 'Imagine™ %s', '%s HD', '%s with Friends', '%s: Anniversary', '%s 7',
    'The Legend of %s', '%s: Evolution', 'Call of Duty: %s', '%s: Redemption', '%s United',
    '%s! - The Quest for Gravity', '%s!!! - A Reckless Disregard for Gravity', '%s: Hot Pursuit',
    '%s: Fusion', '%s: Second Edition', '%s: Make Blooms Not War', '%s: Armageddon', '%s: Guerrilla',
    '%s Nitro', '%s: Vice City', 'Return to %s', '%s at the Inventory', '%s: Deathmatch', '%s 11',
    '%s: 1942', 'IL-2 Sturmovik: %s', '%s+', '%s: Condition Zero', '%s Deluxe', '%s in Trouble',
    '%s of Might and Magic', '%s Classic', '%s: Invisible War', '%s: Source', '%s II', '%s III',
    '%s XIV', '%s DS', '%s 64', '%s: Advanced Pack', '%s: Team Arena', '%s: Arena', '%s 6',
    '%s: Ground Zero', "%s: An Item Shop's Tale", '%s 2013', '%s 2048', '%s: Shadow of Chernobyl',
    '%s: Call of Pripyat', "Sid Meier's %s", '%s: Beyond the Sword', '%s: Warlords', 'Shogun: %s',
    '%s: The Ultimate in Mayonaka Arena', 'The Wonderful %s', '%s 2004', '%s 3D', '%s IV', '%s V',
    '%s: Terror from the Deep', "Peter Jackson's %s: The Official Game of the Movie", '%s VII',
    '%s: Championship Edition', 'Super %s', '%s: Total War', '%s: Revelations', '%s: The Game',
    '%s: The Movie: The Game', '%s Fever', '%s: Tricky', '%s: Future', 'Where in the World is %s?',
    '%s: Blood on the Sand', '%s: Mercenaries', '%s!', '%s!?', '%s Euromix', '%s Chronicles',
    '%s: Elite', 'Theatrhythm: %s', '%s: Rio', '%s Legends', '%s: Seasons', '%s in SPACE!',
    '%s: Over the Road Racing', '%s Gemini', 'Elite %s', 'Area 51: %s', '%s: Touch', '%s DX',
    'No One Can Stop %s', 'Feel the Magic: %s', 'Knights of %s', 'Codename: %s', "%s '13",
    '%s: Blood Money', '%s Rearmed', '%s: Peace Walker', '%s Remix', '%s ZX', 'Extreme %s',
    '%s Extreme', 'I Wanna Be the %s', 'Escape from %s', 'Batman: %s', "Cabela's %s", "%s: XX/XY",
    'Race Driver: %s', 'BlazBlue: %s', 'Need for Speed: %s', '%s Unlimited', '%s Z', "NBA %s",
    "Tom Clancy's %s", 'Spider-Man %s', "Dynasty Warriors: %s", "James Bond %s", '%s Golf',
    "Ratchet & Clank: %s", 'Heroes of %s', 'Dora the Explorer: %s', 'Duke Nukem: %s', 'WWE: %s',
    'Littlest %s', '%s Resort', 'LEGO %s', '%s Online', 'Command & Conquer: %s', '%s: Impact',
    'Rayman: %s', 'Kane & Lynch: %s', '%s Wrestling', '%s Toshinden', 'Ghost Recon: %s', "%s '11",
    '%s: Tactics', 'Virtual %s', 'Professor Layton and the %s', '%s Zone', '%s: The Show',
    'NCAA %s', '%s Advance', '%s Simulator', '%s and How it Hits the Forest', '%s Forever',
    '%s at War', "Tony Hawk %s", 'My %s', 'myNotebook %s', '%sVille', '%s: Warped', '%s Reloaded',
    'Buzz! %s', '%s Jr.', '%s Rising', '%s Red Version', '%s Blue Version', '%s Zero', '%s Climax',
    '%s at the Olympic Games', '%s Turbo', '%s 2000', '%s 3000', '%s: Insect Armageddon',
    '%s Black Label', '%s: Touched!'
    ]

company = ['Lionhead', 'Microsoft', 'Sony', 'Polytron', 'Sega', 'Nintendo', 'Activision', 'EA',
    'Bioware', 'Bethesda', 'Valve', 'From Software', 'Double Fine', 'Gameloft', 'Zynga', '22 Cans',
    'Carbon Neutral Games', 'Harmonix', 'Neversoft', 'Mojang', 'Dejobaan', 'Telltale Games',
    'Oddworld Inhabitants', 'Cipher Prime', 'LucasArts', 'thatgamecompany', 'Access Games',
    'Media Molecule', 'Team Meat', 'Rockstar North', 'Team Bondi', 'Bizarre Creations',
    'Epic Games', 'Disney Interactive', 'Ubisoft', '1C Company', 'Konami', 'THQ', 'Atari', 'Capcom',
    'Namco Bandai', 'Platinum Games', 'Square Enix', 'Codemasters', 'Majesco', 'Atlus', 'Eidos',
    '5th Cell', 'GRIN', 'KOEI', 'Take-Two', 'Tecmo', 'Pony Canyon', 'ValuSoft', '2K Games',
    'Aksys Games', 'EA Sports', 'PopCap', 'Arc System Works', 'Data East', 'Rare', 'Videlectrix',
    'The Game Factory', 'MicroProse', 'id', 'Meridian4', 'Digital Leisure', 'Taito', 'SNK Playmore',
    'Midway', 'Sierra', 'Banpresto', 'Maxis', 'HAL Laboratory', 'Hudson', 'Sonic Team',
    'Vicarious Visions', 'Team17', 'Acclaim', 'SunSoft', 'Crytek', 'Rovio', 'Penny Arcade',
    'Runic Games', 'Infinity Ward', 'Insomniac', 'Treyarch', 'Respawn Entertainment',
    'Inti Creates', 'Overdrive', 'Supergiant Games', '2D Boy', 'Twisted Pixel', 'Chronic Logic',
    'Eurocom', 'Firefly Studios', 'Frontier Developments', 'Gaijin Games', 'Frictional Games',
    'Grasshopper', 'Introversion', 'Level-5', 'Llamasoft', 'Metanet Software', 'Mousechief',
    'Nifflas', 'Playdead', 'Q-Games', 'Queasy Games', 'Studio Pixel', 'Blizzard', 'inXile',
    'NCsoft', 'Nippon Ichi Software', 'Rockstar', 'Stardock', 'XSEED Games', 'Two Tribes',
    "Traveller's Tales", 'Naugty Dog', 'WayForward', 'CINEMAX', 'Nnooo', 'Bullfrog',
    'Bohemia Interactive', 'Game Freak', 'Sledgehammer Games', 'VectorCell', 'Edge Games',
    'Illusion', 'Dark Energy Digital', 'Rising Star Games'
    ]

story = [
    'Our sources inform us that <company> are aiming to ship <game> next holiday season.',
    'Enraged fans are petitioning <company> to "fix" the ending of <game>.',
    '<company> have announced a Kickstarter campaign to fund the development of <game>.',
    'The internet is today angry at <company> after it is revealed that <game> shipped with DLC on-disk.',
    "After shipping the PC version of <game> on Steam, <company> tell us that they couldn't be happier with its new home.",
    "Protestors are picketing the offices of <company> today after the discovery of a hidden sex minigame in <game>.",
    "<company> have been forced to lay off hundreds of employees due to the poor Metacritic performance of <game>.",
    "<company> have issued a global recall of <game> following the discovery that it contains potentially offensive religious content.",
    "Gamers rejoice! After fifteen years in development, <company> have finally released <game>.",
    '<game> recently hit ten million sales in the iPhone App Store. <company> are "delighted".',
    "<company> have declined to comment after many of the art assets in <game> are proven to have been stolen.",
    "Discover why <game> signals the beginning of the end for <company> in our comprehensive review.",
    "An anonymous <company> employee has started a blog documenting the poor working conditions on the <game> team.",
    "The open-source project <game> has been forked after its founder sold the name to <company>.",
    "Local flooding has forced <company> to announce that <game> will ship later than expected.",
    "<company> will not be attending E3 this year. They have instead opted to host their own event to promote <game>.",
    "For the first time, <company> will be shipping a game — <game> — on a console besides their own.",
    "<company> have released a trailer for their new anime adaptation <game>.",
    "In a move to bring back the genre that made them famous, <company> today announced their new project <game>.",
    "A new Humble Bundle debuts today. The highlight of the lineup is <company>'s new title, <game>.",
    "Despite prior promises otherwise, <game> shipped on Steam today with <company>'s always-connected DRM system.",
    "<company> today confirmed that <game> will be a Kinect exclusive.",
    "<company> are being criticised on NeoGAF over the handling of microtransactions in <game>.",
    "Despite <company>'s billion-dollar marketing push, <game> sold fewer than ten thousand copies in its first week on sale.",
    "Shareholders are reportedly angry at <company> over their handling of <game>.",
    "<game> has been nominated for over two hundred Game of the Year awards. <company> have sent representatives around the world to collect every single one.",
    "<company>, developers of critic's darling <game>, have been purchased by CBS Interactive.",
    "Notch has offered <company> an effective blank check to fund the development of a sequel to <game>.",
    "The tear-jerking viral YouTube video in which a bedridden child plays <game> in her last hours alive has been proven fake. <company> have apologised for misleading the public.",
    "<company> are no longer under threat of hostile takeover after the runaway success of <game>.",
    "Ex-<company> employees are frustrated about their exclusion from the credits of <game>.",
    "<company> have confirmed that <game> will ship when planned and multiplayer will be patched in post-release.",
    "Controversy unfolds as <company> are criticised for marketing their adult visual novel <game> to minors.",
    "<company> have sold the rights to make a movie of <game> to an undisclosed third party.",
    "<company> are playing down the importance of the recent leak of <game>'s script months before it is due to be released.",
    "Rumours are circulating that <company> are going to announce <game> at a publisher event next week.",
    "After a spate of negative user reviews on Metacritic, <company> have reached out to players of <game> to rebalance the average score.",
    "About to board a plane to <company>'s offices, where he thought he was getting an interview, police today arrested the hacker responsible for last year's <game> leak.",
#    "<company>'s forthcoming title <game> has been pushed back to be released as a PlayStation 4 launch title.",
    "<company> are being criticised over a sequence in <game> in which players are encouraged to engage in a terrorist act.",
    "Record returns follow record sales and <company> send millions of copies of <game> to landfill."
    ]
